name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Dependency - libbluetooth-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libbluetooth-dev
      - name: Dependency - gattlib
        run: |
          git clone https://github.com/labapart/gattlib.git
          cd gattlib && mkdir build && cd build && cmake -DGATTLIB_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=Release ..  && make
          sudo make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: |
          mkdir build && cd build && cmake .. && make
          sudo make install
